name : Assessment CI

on:
 push:
  paths:
   - "Week-6/Day3/**
   - ".github/workflows/assessment.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/version@v4

     - name: Install Python
       uses: actions/python@v5
       with: 
        python-version : "3.12"

     - name: Install dependencies
       run: pip install -r "Week-6/requirements.txt"

     - name: Run Tests
       run: python -m pytest
       working-directory: Week-6/Day3

     - name: run ruff
       run: pip install ruff
            ruff check.
       working-directory: Week-6/Day3

     - name: doker add
       run: docker build t -Day6 ./Week-6/Day3
       
     - name: upload acticfact
       run : mkdir artifact
          cp -r Week-6/Day3/app artifact/
          cp -r Week-6/Day3/tests artifact/
          cp Week-6/Day3/requirements.txt artifact/

     - name: doenload acticfact
       uses: actions/upload-artifact@v4
       with: 
        name: assessment
        path: artifact