name: CI Deployment

on:
 push:
  paths:
    - "Week-6/Day3/**"
    - ".github/workflows/day5-deploy.yml"

jobs:
  test:
   runs-on: ubuntu-latest
 
   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version : "3.12"

    - name: Install dependencies
      run: pip install -r Week-6/Day3/requirements.txt

    - name: Run tests
      run: python -m pytest
      working-directory: Week-6/Day3

  build:
   needs: test

   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t day5-fastapi ./Week-6/Day3 