name: New CI Practice

on:
  push:
    paths:
      - "Week-6/Day3/**"
      - ".github/workflows/practice-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r Week-6/Day3/requirements.txt

      - name: Run test
        run: python -m pytest
        working-directory: Week-6/Day3
      
      - name: Create artifact
        run: |
          mkdir artifact
          cp -r Week-6/Day3/app artifact/
          cp -r Week-6/Day3/tests artifact/
          cp Week-6/Day3/requirements.txt artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: day3-application
          path: Week-6/Day3/artifact
